project_id = "mpvcadyicshblhleoyob"

[functions.kiosk-auth]
verify_jwt = false

[functions.send-whatsapp-otp]
verify_jwt = false

[functions.verify-whatsapp-otp]
verify_jwt = false

[functions.create-room-session]
verify_jwt = false

[functions.join-room-queue]
verify_jwt = false

[functions.process-room-queue]
verify_jwt = false

[functions.sizing-api-proxy]
verify_jwt = false