// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mpvcadyicshblhleoyob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1wdmNhZHlpY3NoYmxobGVveW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzcxMTEsImV4cCI6MjA3MDg1MzExMX0.x68sZnBQN1c7MmAjHR-dLdxUWt2lU2tN4IV7wX4mCEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});